### ISSUE TITLE
Easy way to compare arrays?

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#72] opened 2019-06-02 20:28 UTC
I tried 

```ts
const array: f64[] = [20.0,30.0,0,0,0,0]
expect<f64[]>(array).toBe([20.0,30.0,0,0,0,0])
```

which may not even be the same types of array, but I realized that this compares them by reference (obviously it would fail).

Is there an API to easily compare arrays? Or should I loop on the indexes and use expect on each value for now?

**Comment by jtenner** [comment] 2019-06-02 21:30
No there is no api to match arrays. The reason is because arrays have an underlying reference to an arraybuffer. We can't just compare Array references because the property is private, and we don't know the shape up front. We could modify the comparison to account for inspection on arrays of exactly the same type. 

The problem is that if the expectation compares a type T which is Array<U>, we cannot get a type reference to U. I can't determine if U is a value type or a reference. Worse, I cannot compare child references. 

For now, you can use the `@operator("==")` syntax to perform custom equality assertions on hand crafted classes. Sadly, this doesn't exist for Arrays. 

In due time.

**Comment by trusktr** [comment] 2019-06-03 00:37
The operator overloads look cool, but I'm interested in writing portable code, so it looks like that might not be an option for me. For now I'll loop on the array. :)

**Comment by jtenner** [comment] 2019-06-03 03:03
It's meaningful to write portable code! Good luck.

**Comment by jtenner** [comment] 2019-06-03 13:29
@trusktr this issue deserves a meaningful solution in the short term, and I will fix this on whatever branch I decide to use.  Currently I'm deciding between `runtime` and `wasm-runner` because I don't know if I should put all the test running logic inside AssemblyScript.

**Comment by jtenner** [comment] 2019-06-03 15:14
Please see `assembly/__tests__/toStrictEqual.spec.ts` for usage example. I have disabled the use of `Array<T>` such that `T` is a reference. This is because logging an array of references is not very intuitive, and a simple custom hand-written function would be better in that case. However, for your purposes, it's probably best to use the `toStrictEqual` function.

I have fixed this on the runtime branch, and would like your input.

**Comment by jtenner** [comment] 2019-06-03 16:44
This will be addressed partially in #62.

Full feature support for `Array<T>`  where `T` is managed cannot be supported meaningfully yet.

**Comment by jtenner** [comment] 2019-06-06 13:39
@trusktr I don't exactly know how to make this more useful, but when comparing `Array<T>` such that `T` is a managed type, it's possible to use the `operator("==")` decorator and use a custom assertion just for this purpose.

Otherwise, number values are compared correctly now.

**Comment by trusktr** [comment] 2019-06-07 22:18
sweeeet. I'll swing back around to try it a little later.

**Comment by jtenner** [comment] 2019-06-08 19:08
I haven't closed this issue because I want to enable array of references comparisons.

Since we cannot get the programmatic offset of the child type, we cannot use memcompare because we need the size of the block. We can only opt into block comparisons for strings and array buffers and access their size at runtime. This will be supported in the 1.1.0 release. 

Once `typeof` support exists in the compiler, we will enable regular reference comparisons.

In 1.1.0 they will default to `==` comparisons, which can be overridden using `@operator("==")`. This does not help people who want to use portable code, but aspect is burgeoning and I don't mind enabling support for this later.

**Comment by trusktr** [comment] 2019-06-11 08:16
> array of references

Got a example snippet of an "array of references"?

**Comment by jtenner** [comment] 2019-06-11 09:06
Please see the toStrictEqual test suite located in the assembly/__tests__

Each one of those examples is your best friend to figuring out how the library works.

**Closed** 2019-06-11 13:03 UTC
Labels: completed, enhancement

**Comment by trusktr** [comment] 2019-06-12 08:10
I see the [toStrictEqual tests](https://github.com/jtenner/as-pect/blob/7a915596287c3ea939f1fa31b7708867dea21428/assembly/__tests__/toStrictEqual.spec.ts). 
I just wasn't sure of terminology. So "array of references" is just an array of objects. Is there such thing as "array of pointers" in AS? Or is that the same thing on the AS user side?

**Comment by jtenner** [comment] 2019-06-12 11:10
Yes. `usize[]`

This is essentially an array of i32. It gets compared directly. 

Why don't you start submitting pull requests for the Readme? You have lots of questions.

**Comment by trusktr** [comment] 2019-06-13 04:05
That seems like a good idea once I understand enough. :)

**Comment by trusktr** [comment] 2019-06-13 04:05
I'm still fumbling around, f.e. https://github.com/AssemblyScript/assemblyscript/issues/645
