### ISSUE TITLE
Actual and Expected references are retained after a test has completed

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#86] opened 2019-06-11 15:29 UTC

**Comment by jtenner** [comment] 2019-06-11 15:35
Yeah this reports `+2` references on tests that should be properly cleaned up. I have reproduced the problem locally and it will be fixed in `1.1.1`.

**Comment by jtenner** [comment] 2019-06-12 15:57
There is no way to determine which `Expectation`s need to be released. After a lot of talk with @dcode, I decided that the only thing I can do is perform a `__release` on actual and expected values.

There are no good tools for solving this problem just yet, and it's probably best to leave it be until the compiler gives us more tools to help with reference cleanup involving `unreachable()`.

Instead, the best solution now would be to point out that `unreachable()` instructions will leak every reference that is currently active. Each Array has two references (the array and the underlying buffer) plus the expectation that was allocated to hold the `actual` value data. Even releasing `Actual.reference` will not free this memory because it's still attached to the `Expectation`.

The expected value is not stored on the heap and will be collected.

**Closed** 2019-06-14 15:08 UTC
Labels: bug, completed
