### ISSUE TITLE
RuntimeError: unreachable

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#81] opened 2019-06-10 07:08 UTC
Any thoughts on this one? https://github.com/AssemblyScript/assemblyscript/issues/649 Not sure if it's coming from as-pect or assemblyscript.

The error is happening in this test: https://github.com/infamous/glas/blob/assemblyscript-issue-649/src/as/glas/math/Color.spec.ts#L74

**Comment by jtenner** [comment] 2019-06-10 17:07
https://github.com/infamous/glas/blob/assemblyscript-issue-649/src/as/glas/math/Color.spec.ts#L76

It does appear you are using an object literal. I didn't think these were supported in `AssemblyScript`.

**Comment by trusktr** [comment] 2019-06-11 06:42
Aaah, looks like maybe asc should have a more helpful error in that case.

**Comment by trusktr** [comment] 2019-06-11 07:02
Hmmm, looks like the object literals are supported when they are typed as a class: https://github.com/AssemblyScript/assemblyscript/issues/633#issuecomment-499359300

**Comment by trusktr** [comment] 2019-06-11 07:36
Ah! The problem seems to be that the `describe` block does not have an `it` or `test`.

So when I changed the test to the following, it worked great (test compiled):

```ts
	describe('setHSL', () => {
		it('sets color from HSL values', () => {
			const c = new Color()
			const hsl: HSL = {h: 0, s: 0, l: 0}

			c.setHSL(0.75, 1.0, 0.25)
			c.getHSL(hsl)

			expect<f64>(hsl.h).toBe(0.75)
			expect<f64>(hsl.s).toBe(1.0)
			expect<f64>(hsl.l).toBe(0.25)
		})
	})
```

Looks like using `expect` outside of the `it`/`test` blocks causes the error. So if I change it to the following, then there's no error:

```ts
	describe('setHSL', () => {
		const c = new Color()
		const hsl: HSL = {h: 0, s: 0, l: 0}

		c.setHSL(0.75, 1.0, 0.25)
		c.getHSL(hsl)
	})
```

Maybe there just needs to be a more helpful error in the case someone forgets an it/test block?

**Comment by jtenner** [comment] 2019-06-11 09:34
Ah. Nice catch. Yes. This is by design.

In order to report an actual or expected value, there must be a test. Currently, if there is an expect outside of a test block, the file fails, generating an error.

The SummaryTestReporter should have showing errors on by default and this would fix it.

**Comment by trusktr** [comment] 2019-06-11 16:15
Makes sense. Something other than "RuntimeError: unreachable" would be more helpful. Maybe something like "expec() must be used inside an it() or test() block".

**Comment by jtenner** [comment] 2019-06-11 18:29
I have added error and warning output to stdout for the `SummaryTestReporter`. Should be fixed in #87

**Comment by trusktr** [comment] 2019-06-12 03:31
Cool. By the way, I noticed that in some cases, even if missing `it()` or `test()`, the tests still pass. 

So basically, without `it` or `test` inside of describe, one of three can happen:

- test don't pass
- compile fails
- tests pass (most uncommon)

I'll keep an eye out once I update as-pect. Burning through code porting. Can't wait to get the rotating box on the screen!

**Comment by jtenner** [comment] 2019-06-13 13:40
@trusktr I managed to replicate a problem with this exact error. I finally understand why this problem exists.

When an error occurs, regardless of how, during test collection, it causes a runtime error and the process exits `code 1`  without running the rest of the test suites, reporting `RuntimeError: unreachable`.

This is very fixable, and I have the infrastructure in place to make this happen quickly.

Please wait until tomorrow and you should be able to try out the configuration-warning branch.

Way to reproduce this error is:

```ts
describe("something", () => {
  unreachable();
});
```

**Comment by jtenner** [comment] 2019-06-13 15:23
The `errors` array on the `TestContext` now correctly report the problem:

```
        Object {
          "message": "TestCollectionError: This is an error message.",
          "stackTrace": "RuntimeError: unreachable
          at start:assembly/jest-invalid-expectation~anonymous|1 (wasm-function[72]:18)
          at assembly/internal/Describe/describe (wasm-function[70]:16)
          at start:assembly/jest-invalid-expectation (wasm-function[73]:13)
          at start (wasm-function[82]:12)",
          "type": "TestCollectionError",
        }
```

The lack of description is a limitation of Web Assembly and AssemblyScript if the instruction

**Closed** 2019-06-14 15:08 UTC
Labels: bug, completed
